### PR TITLE
Resolve failing cloudbuilds, update yarn release target to use new shadowcljs build name

### PR DESCRIPTION
**Pull request by theferrit32**

### CODE REVIEW

**Comment by theferrit32** [comment]
Actually not sure that this will resolve the current cloudbuild failures, but it will resolve others

**Comment by sjahl** [comment]
The current build failure in staging is complaining about yarn packages being out of date in the yarn.lock file. We throw `--frozen-lockfile` there to ensure that we don't upgrade any packages during the CI pipeline, and that flag stops the install with an error if there's packages that need update. So, updating and committing a new yarn.lock should fix the staging build.

The build failures in dev are from the cloudbuilder trying to pull the yarn-builder image from the clingen-stage GCR repo, which it doesn't have permission to do. I can look into what's required there to allow the -dev env to pull that image.

**Comment by theferrit32** [comment]
@sjahl I'm working on updating the yarn.lock but some package `sse4_crc32` is failing to build, I think the npm package itself is broken because it fails to build on both ubuntu and mac.

I also just disabled the cloudbuild trigger on clingen-dev. I'm just doing manual deploys to the dev environment, so I think just having the automated ones go to staging is okay.

**Comment by sjahl** [comment]
If it's useful to do dev builds in cloudbuild once in a while (manually or via some trigger), i think we can make the GCR registry name a variable in cloudbuild, so that dev builds would use a `gcr.io/clingen-dev/yarn-builder` image. That would save us from needing to grant the dev env read access to the staging registry.

If running cloudbuilds in dev is not regular or useful, I can forget about that for now 😄

**Comment by theferrit32** [comment]
Okay it looks like there is a cloudbuild variable `PROJECT_ID`. We could use that in other lines as well.

https://github.com/clingen-data-model/curator/blob/4e88e9031bf99e6a919c938ef1506414e985c5a8/cloudbuild.yaml#L9

and here if we change the name of the build targets from `app-stage` to `clingen-stage`, etc

https://github.com/clingen-data-model/curator/pull/23/files#diff-0b4a5fc26445836e6672c426692297004cfaba21997343b63e6f58b946bd2a5cR7

For dev it would be useful to trigger manual cloudbuilds. My home internet download and particularly upload speed is not very good so doing local docker builds and pushes takes a while.

**Comment by sjahl** [comment]
OK -- I just built a yarn-builder for clingen-dev and am pushing it. I'm also updating and pushing the -stage version so that both environments are using the same thing.

My home upload is also slow, so it'll take a bit for them to show up.

**Comment by theferrit32** [comment]
`clingen-stage` build triggered by this merge was successful

**Pull request merged**
